 /******************************************************************************
 *
 * Module: Port 
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Youssef Samy Hassan
 ******************************************************************************/

#include "Port.h"
#include "MemMap.h"
/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */

#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif
/* PB structure used with Port_Init API */
   const Port_ConfigType Port_configration = {
                                                 PORTA_PIN0_ID_NUM,PORTA_PIN0_MODE,PORTA_PIN0_DIR,PORTA_PIN0_INITIAL_VALUE,PORTA_PIN0_INTERNAL_RESESTOR,PORTA_PIN0_DIR_CHANGABLE,PORTA_PIN0_MODE_CHANGABLE,	
                                                 PORTA_PIN1_ID_NUM,PORTA_PIN1_MODE,PORTA_PIN1_DIR,PORTA_PIN1_INITIAL_VALUE,PORTA_PIN1_INTERNAL_RESESTOR,PORTA_PIN1_DIR_CHANGABLE,PORTA_PIN1_MODE_CHANGABLE,   
                                                 PORTA_PIN2_ID_NUM,PORTA_PIN2_MODE,PORTA_PIN2_DIR,PORTA_PIN2_INITIAL_VALUE,PORTA_PIN2_INTERNAL_RESESTOR,PORTA_PIN2_DIR_CHANGABLE,PORTA_PIN2_MODE_CHANGABLE,   
                                                 PORTA_PIN3_ID_NUM,PORTA_PIN3_MODE,PORTA_PIN3_DIR,PORTA_PIN3_INITIAL_VALUE,PORTA_PIN3_INTERNAL_RESESTOR,PORTA_PIN3_DIR_CHANGABLE,PORTA_PIN3_MODE_CHANGABLE,   
                                                 PORTA_PIN4_ID_NUM,PORTA_PIN4_MODE,PORTA_PIN4_DIR,PORTA_PIN4_INITIAL_VALUE,PORTA_PIN4_INTERNAL_RESESTOR,PORTA_PIN4_DIR_CHANGABLE,PORTA_PIN4_MODE_CHANGABLE,                                                
                                                 PORTA_PIN5_ID_NUM,PORTA_PIN5_MODE,PORTA_PIN5_DIR,PORTA_PIN5_INITIAL_VALUE,PORTA_PIN5_INTERNAL_RESESTOR,PORTA_PIN5_DIR_CHANGABLE,PORTA_PIN5_MODE_CHANGABLE,                                                   
                                                 PORTA_PIN6_ID_NUM,PORTA_PIN6_MODE,PORTA_PIN6_DIR,PORTA_PIN6_INITIAL_VALUE,PORTA_PIN6_INTERNAL_RESESTOR,PORTA_PIN6_DIR_CHANGABLE,PORTA_PIN6_MODE_CHANGABLE,
                                                 PORTA_PIN7_ID_NUM,PORTA_PIN7_MODE,PORTA_PIN7_DIR,PORTA_PIN7_INITIAL_VALUE,PORTA_PIN7_INTERNAL_RESESTOR,PORTA_PIN7_DIR_CHANGABLE,PORTA_PIN7_MODE_CHANGABLE,
                                                 
                                                 PORTB_PIN0_ID_NUM,PORTB_PIN0_MODE,PORTB_PIN0_DIR,PORTB_PIN0_INITIAL_VALUE,PORTB_PIN0_INTERNAL_RESESTOR,PORTB_PIN0_DIR_CHANGABLE,PORTB_PIN0_MODE_CHANGABLE,
                                                 PORTB_PIN1_ID_NUM,PORTB_PIN1_MODE,PORTB_PIN1_DIR,PORTB_PIN1_INITIAL_VALUE,PORTB_PIN1_INTERNAL_RESESTOR,PORTB_PIN1_DIR_CHANGABLE,PORTB_PIN1_MODE_CHANGABLE,                                                
                                                 PORTB_PIN2_ID_NUM,PORTB_PIN2_MODE,PORTB_PIN2_DIR,PORTB_PIN2_INITIAL_VALUE,PORTB_PIN2_INTERNAL_RESESTOR,PORTB_PIN2_DIR_CHANGABLE,PORTB_PIN2_MODE_CHANGABLE,                                               
                                                 PORTB_PIN3_ID_NUM,PORTB_PIN3_MODE,PORTB_PIN3_DIR,PORTB_PIN3_INITIAL_VALUE,PORTB_PIN3_INTERNAL_RESESTOR,PORTB_PIN3_DIR_CHANGABLE,PORTB_PIN3_MODE_CHANGABLE,
                                                 PORTB_PIN4_ID_NUM,PORTB_PIN4_MODE,PORTB_PIN4_DIR,PORTB_PIN4_INITIAL_VALUE,PORTB_PIN4_INTERNAL_RESESTOR,PORTB_PIN4_DIR_CHANGABLE,PORTB_PIN4_MODE_CHANGABLE,
                                                 PORTB_PIN5_ID_NUM,PORTB_PIN5_MODE,PORTB_PIN5_DIR,PORTB_PIN5_INITIAL_VALUE,PORTB_PIN5_INTERNAL_RESESTOR,PORTB_PIN5_DIR_CHANGABLE,PORTB_PIN5_MODE_CHANGABLE,
                                                 PORTB_PIN6_ID_NUM,PORTB_PIN6_MODE,PORTB_PIN6_DIR,PORTB_PIN6_INITIAL_VALUE,PORTB_PIN6_INTERNAL_RESESTOR,PORTB_PIN6_DIR_CHANGABLE,PORTB_PIN6_MODE_CHANGABLE,
                                                 PORTB_PIN7_ID_NUM,PORTB_PIN7_MODE,PORTB_PIN7_DIR,PORTB_PIN7_INITIAL_VALUE,PORTB_PIN7_INTERNAL_RESESTOR,PORTB_PIN7_DIR_CHANGABLE,PORTB_PIN7_MODE_CHANGABLE,
                                                 
                                                 PORTC_PIN0_ID_NUM,PORTC_PIN0_MODE,PORTC_PIN0_DIR,PORTC_PIN0_INITIAL_VALUE,PORTC_PIN0_INTERNAL_RESESTOR,PORTC_PIN0_DIR_CHANGABLE,PORTC_PIN0_MODE_CHANGABLE,
                                                 PORTC_PIN1_ID_NUM,PORTC_PIN1_MODE,PORTC_PIN1_DIR,PORTC_PIN1_INITIAL_VALUE,PORTC_PIN1_INTERNAL_RESESTOR,PORTC_PIN1_DIR_CHANGABLE,PORTC_PIN1_MODE_CHANGABLE,
                                                 PORTC_PIN2_ID_NUM,PORTC_PIN2_MODE,PORTC_PIN2_DIR,PORTC_PIN2_INITIAL_VALUE,PORTC_PIN2_INTERNAL_RESESTOR,PORTC_PIN2_DIR_CHANGABLE,PORTC_PIN2_MODE_CHANGABLE,
                                                 PORTC_PIN3_ID_NUM,PORTC_PIN3_MODE,PORTC_PIN3_DIR,PORTC_PIN3_INITIAL_VALUE,PORTC_PIN3_INTERNAL_RESESTOR,PORTC_PIN3_DIR_CHANGABLE,PORTC_PIN3_MODE_CHANGABLE,
                                                 PORTC_PIN4_ID_NUM,PORTC_PIN4_MODE,PORTC_PIN4_DIR,PORTC_PIN4_INITIAL_VALUE,PORTC_PIN4_INTERNAL_RESESTOR,PORTC_PIN4_DIR_CHANGABLE,PORTC_PIN4_MODE_CHANGABLE,
                                                 PORTC_PIN5_ID_NUM,PORTC_PIN5_MODE,PORTC_PIN5_DIR,PORTC_PIN5_INITIAL_VALUE,PORTC_PIN5_INTERNAL_RESESTOR,PORTC_PIN5_DIR_CHANGABLE,PORTC_PIN5_MODE_CHANGABLE,
                                                 PORTC_PIN6_ID_NUM,PORTC_PIN6_MODE,PORTC_PIN6_DIR,PORTC_PIN6_INITIAL_VALUE,PORTC_PIN6_INTERNAL_RESESTOR,PORTC_PIN6_DIR_CHANGABLE,PORTC_PIN6_MODE_CHANGABLE,
                                                 PORTC_PIN7_ID_NUM,PORTC_PIN7_MODE,PORTC_PIN7_DIR,PORTC_PIN7_INITIAL_VALUE,PORTC_PIN7_INTERNAL_RESESTOR,PORTC_PIN7_DIR_CHANGABLE,PORTC_PIN7_MODE_CHANGABLE,
                                                 
                                                 PORTD_PIN0_ID_NUM,PORTD_PIN0_MODE,PORTD_PIN0_DIR,PORTD_PIN0_INITIAL_VALUE,PORTD_PIN0_INTERNAL_RESESTOR,PORTD_PIN0_DIR_CHANGABLE,PORTD_PIN0_MODE_CHANGABLE,
                                                 PORTD_PIN1_ID_NUM,PORTD_PIN1_MODE,PORTD_PIN1_DIR,PORTD_PIN1_INITIAL_VALUE,PORTD_PIN1_INTERNAL_RESESTOR,PORTD_PIN1_DIR_CHANGABLE,PORTD_PIN1_MODE_CHANGABLE,
                                                 PORTD_PIN2_ID_NUM,PORTD_PIN2_MODE,PORTD_PIN2_DIR,PORTD_PIN2_INITIAL_VALUE,PORTD_PIN2_INTERNAL_RESESTOR,PORTD_PIN2_DIR_CHANGABLE,PORTD_PIN2_MODE_CHANGABLE,
                                                 PORTD_PIN3_ID_NUM,PORTD_PIN3_MODE,PORTD_PIN3_DIR,PORTD_PIN3_INITIAL_VALUE,PORTD_PIN3_INTERNAL_RESESTOR,PORTD_PIN3_DIR_CHANGABLE,PORTD_PIN3_MODE_CHANGABLE,
                                                 PORTD_PIN4_ID_NUM,PORTD_PIN4_MODE,PORTD_PIN4_DIR,PORTD_PIN4_INITIAL_VALUE,PORTD_PIN4_INTERNAL_RESESTOR,PORTD_PIN4_DIR_CHANGABLE,PORTD_PIN4_MODE_CHANGABLE,
                                                 PORTD_PIN5_ID_NUM,PORTD_PIN5_MODE,PORTD_PIN5_DIR,PORTD_PIN5_INITIAL_VALUE,PORTD_PIN5_INTERNAL_RESESTOR,PORTD_PIN5_DIR_CHANGABLE,PORTD_PIN5_MODE_CHANGABLE,
                                                 PORTD_PIN6_ID_NUM,PORTD_PIN6_MODE,PORTD_PIN6_DIR,PORTD_PIN6_INITIAL_VALUE,PORTD_PIN6_INTERNAL_RESESTOR,PORTD_PIN6_DIR_CHANGABLE,PORTD_PIN6_MODE_CHANGABLE,
                                                 PORTD_PIN7_ID_NUM,PORTD_PIN7_MODE,PORTD_PIN7_DIR,PORTD_PIN7_INITIAL_VALUE,PORTD_PIN7_INTERNAL_RESESTOR,PORTD_PIN7_DIR_CHANGABLE,PORTD_PIN7_MODE_CHANGABLE,
                                                 
                                                 PORTE_PIN0_ID_NUM,PORTE_PIN0_MODE,PORTE_PIN0_DIR,PORTE_PIN0_INITIAL_VALUE,PORTE_PIN0_INTERNAL_RESESTOR,PORTE_PIN0_DIR_CHANGABLE,PORTE_PIN0_MODE_CHANGABLE,
                                                 PORTE_PIN1_ID_NUM,PORTE_PIN1_MODE,PORTE_PIN1_DIR,PORTE_PIN1_INITIAL_VALUE,PORTE_PIN1_INTERNAL_RESESTOR,PORTE_PIN1_DIR_CHANGABLE,PORTE_PIN1_MODE_CHANGABLE,
                                                 PORTE_PIN2_ID_NUM,PORTE_PIN2_MODE,PORTE_PIN2_DIR,PORTE_PIN2_INITIAL_VALUE,PORTE_PIN2_INTERNAL_RESESTOR,PORTE_PIN2_DIR_CHANGABLE,PORTE_PIN2_MODE_CHANGABLE,
                                                 PORTE_PIN3_ID_NUM,PORTE_PIN3_MODE,PORTE_PIN3_DIR,PORTE_PIN3_INITIAL_VALUE,PORTE_PIN3_INTERNAL_RESESTOR,PORTE_PIN3_DIR_CHANGABLE,PORTE_PIN3_MODE_CHANGABLE,
                                                 PORTE_PIN4_ID_NUM,PORTE_PIN4_MODE,PORTE_PIN4_DIR,PORTE_PIN4_INITIAL_VALUE,PORTE_PIN4_INTERNAL_RESESTOR,PORTE_PIN4_DIR_CHANGABLE,PORTE_PIN4_MODE_CHANGABLE,
                                                 PORTE_PIN5_ID_NUM,PORTE_PIN5_MODE,PORTE_PIN5_DIR,PORTE_PIN5_INITIAL_VALUE,PORTE_PIN5_INTERNAL_RESESTOR,PORTE_PIN5_DIR_CHANGABLE,PORTE_PIN5_MODE_CHANGABLE,
                                                 
                                                 PORTF_PIN0_ID_NUM,PORTF_PIN0_MODE,PORTF_PIN0_DIR,PORTF_PIN0_INITIAL_VALUE,PORTF_PIN0_INTERNAL_RESESTOR,PORTF_PIN0_DIR_CHANGABLE,PORTF_PIN0_MODE_CHANGABLE,
                                                 PORTF_LED1_ID_NUM,PORTF_LED1_MODE,PORTF_LED1_DIR,PORTF_LED1_INITIAL_VALUE,PORTF_LED1_INTERNAL_RESESTOR,PORTF_LED1_DIR_CHANGABLE,PORTF_LED1_MODE_CHANGABLE,
                                                 PORTF_PIN2_ID_NUM,PORTF_PIN2_MODE,PORTF_PIN2_DIR,PORTF_PIN2_INITIAL_VALUE,PORTF_PIN2_INTERNAL_RESESTOR,PORTF_PIN2_DIR_CHANGABLE,PORTF_PIN2_MODE_CHANGABLE,
                                                 PORTF_PIN3_ID_NUM,PORTF_PIN3_MODE,PORTF_PIN3_DIR,PORTF_PIN3_INITIAL_VALUE,PORTF_PIN3_INTERNAL_RESESTOR,PORTF_PIN3_DIR_CHANGABLE,PORTF_PIN3_MODE_CHANGABLE,
                                                 PORTF_SW1_ID_NUM,PORTF_SW1_MODE,PORTF_SW1_DIR,PORTF_SW1_INITIAL_VALUE,PORTF_SW1_INTERNAL_RESESTOR,PORTF_SW1_DIR_CHANGABLE,PORTF_SW1_MODE_CHANGABLE
					    };